### ISSUE TITLE
require file hxml from a main javacript entry

### ISSUE THREAD

**Issue by francescoagati** [jasononeil/webpack-haxe-loader#1]
hi,
if i have as entry a normal javascript file can i use something like this 
```require('client.hxml')```
requre the file hxml directly from a main js?

**Comment by jasononeil** [comment]
If your normal JS file is processed through webpack then yes, this should
work!

But I haven't actually tested it - let me know if it works okay.

I'll leave this open until we know it works

**Comment by elsassph** [comment]
Yes it will work. You can even export classes/functions/objects using 'Webpack.export'.

**Comment by jasononeil** [comment]
Closing this as it does work :)
