### ISSUE TITLE
recompile with .hx file

### ISSUE THREAD

**Issue by francescoagati** [jasononeil/webpack-haxe-loader#11]
Actually the project is recompiled only if i change the file hxml but not source files with .hx

**Comment by jasononeil** [comment]
That's unusual, for me it recompiles on any dependency change.  Do you have a small project to demonstrate the problem, or a way to reproduce it.

One way to check is if to clone Phillipe's example repo and see if the recompiling works for you there: https://github.com/elsassph/webpack-haxe-example

**Comment by elsassph** [comment]
Loader monitors folders in classpath for reloading. 

- is it in the classpath?
- do you have `-cp` declarations in the `hxml`?

**Comment by jasononeil** [comment]
That's a good point.  If a file is included via having a "-lib" it won't be included in the auto-reload.

**Comment by francescoagati** [comment]
i use poi as a wrapper of webpack. http://poi.js.org. if i change or touch the file .hxml the file are reloaded but if i change a file .hx nothing change.  
Poi is nice because in a zero configuration wrapper around webpack

**Comment by francescoagati** [comment]
no i haven't put -cp in the file .hxml because the Main.hx is in the same root folder

**Comment by francescoagati** [comment]
ok with -cp . it works :-)
thanks
