### ISSUE TITLE
Code splitting and bundle urls

### ISSUE THREAD

**Issue by zabojad** [jasononeil/webpack-haxe-loader#14]
I'm using code splitting along with React Router. My app loads bundles on some urls.

The problem I have is with the depth of those url.

Let's say I have the route `/rt01` of my app that leads to a bundle loading. If I open my browser on `http://localhost:8080/rt01`, webpack dev server will load the bundle from `http://localhost:8080/0.bundle.js` and it will work fine.

However, if I try to open directly `http://localhost:8080/rt01/something/someotherthing`, then webpack dev server will try to load the bundle from `http://localhost:8080/rt01/something/0.bundle.js` and will fail...

How to tell webpack to look for the bundles at an absolute path? Is it a config problem? How to address it?

**Comment by zabojad** [comment]
Oups, sorry for posting to fast. I just needed to precide `output.publicPath` in the webpack config.

**Comment by elsassph** [comment]
Hmm maybe we should add it in our samples to avoid this kind of confusion?

**Comment by zabojad** [comment]
Really, it's more a webpack thing so I don't think it has to be outlined here... Maybe in a `/examples/code-splitting-with-router` sample if you plan to add some in this repo in the future...
