### ISSUE TITLE
Empty `exports`?

### ISSUE THREAD

**Issue by kLabz** [jasononeil/webpack-haxe-loader#18]
I am working with `Webpack.load()` (with haxe react components) and `exports` is always an empty object.

If I add something like
```haxe
$p{['exports', 'default']} = $i{module};
```
before returning `exports`, I can use the component from inside the `.then()` callback, which is what I am looking for.

Am I missing something?

**Comment by elsassph** [comment]
Haxe Loader doesn't add exports for you - you must annotate classes with `@:expose` to populate exports.

**Comment by kLabz** [comment]
Thanks! `@:expose('default')` seems to do the trick.
