### ISSUE TITLE
Integration with hxtsdgen?

### ISSUE THREAD

**Issue by fullofcaffeine** [jasononeil/webpack-haxe-loader#61]
I currently have a hybrid haxe-js/ts experiment app built with webpack. I have a single compiled `hx.js` bundle/module file for the server and another for the client. Both use [hxtsdgen](https://github.com/nadako/hxtsdgen) to generate TS [declaration](https://github.com/fullofcaffeine/fullofcaffeineco-app-boilerplate/blob/master/src/ts/client/hx.d.ts) files. I can then import the `hx` module from TS and webpack will include it in the bundle. I then have some type safety when using my hx module :

https://github.com/fullofcaffeine/fullofcaffeineco-app-boilerplate/blob/master/src/ts/client/App.tsx#L4

It works well enough but the downside is that I need to compile both the haxe client and server bundles *before* the webpack build kicks in (I currently use nodemon to recompile the Haxe bundles and restart the webpack build when hx files change, check [here](https://github.com/fullofcaffeine/fullofcaffeineco-app-boilerplate/blob/master/package.json#L21)), hence I can't take advantage of webpack's watch mode. This slows down the whole build significantly.

I was wondering if I could use this loader and have it integrated with `hxtsdgen` somehow, so that when I require or import the `hxml` from the TS-land, I also have the type info (with the advantage of using solely webpack for the build and being able to use watch for the Haxe bundles too).

Any insights appreciated!

**Comment by elsassph** [comment]
You may want to run a hx watcher kicking the Haxe compilation automatically.

**Comment by fullofcaffeine** [comment]
Hi Philippe,

Thanks for the reply!

What would be the difference between using nodemon? I'm already watching
all hx files, which are then recompiled when changed. But now that you
mention that, I might be able to tweak the configuration so that the Haxe
compilation happens in parallel when hx files change, and then webpack
identifies the resulting js files (compiled by Haxe) changed and just
updates the bundles that use them, instead of restarting the whole webpack
process.

**Comment by elsassph** [comment]
Yes, you can have a watcher on hx files to recompile Haxe to JS and Webpack should pick and rebundle.

**Comment by fullofcaffeine** [comment]
OK, thanks. That should solve my issue without the need to use this loader.

As a related note, do you think it'd make sense to integrate hxtsdgen with this lib?

**Comment by elsassph** [comment]
As I said it's not possible to use hxtsdgen together with the Webpack loader.

**Comment by fullofcaffeine** [comment]
Sorry, for some reason I only received the first paragraph of your answer through the email notification. I now see you added the other part saying it wouldn't be possible.
